<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageId>Wwsrapport.Client</PackageId>
    <Version>0.2.0</Version>
    <Authors>WWSrapport</Authors>
    <Company>WWSrapport</Company>
    <Product>WWSrapport .NET client</Product>
    <Description>Official .NET SDK for the WWSrapport API.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/wwsrapport/dotnet-client</RepositoryUrl>
    <PackageProjectUrl>https://wwsrapport.nl/api/docs</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
