name: tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: dotnet build src/Wwsrapport.Client/Wwsrapport.Client.csproj --configuration Release
      - run: dotnet run --project tests/Wwsrapport.Client.Tests/Wwsrapport.Client.Tests.csproj --configuration Release
